import { createContext, useContext, useState, useEffect, useRef } from 'react'
import api from '../services/api'

const LanguageContext = createContext()

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

// 翻译文本
const translations = {
  'zh-CN': {
    // 通用
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.loading': '加载中...',
    'common.saveSuccess': '保存成功',
    'common.saveFailed': '保存失败',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.actions': '操作',
    'common.back': '返回',
    'common.clear': '清除',
    'common.create': '创建',
    'common.refresh': '刷新',
    
    // 分页
    'pagination.showing': '显示',
    'pagination.of': '共',
    'pagination.items': '条',
    'pagination.firstPage': '首页',
    'pagination.previousPage': '上一页',
    'pagination.nextPage': '下一页',
    'pagination.lastPage': '末页',
    'pagination.itemsPerPage': '每页显示',
    
    // 导航
    'nav.dashboard': '仪表盘',
    'nav.menuManagement': '菜单管理',
    'nav.userManagement': '用户管理',
    'nav.roleManagement': '角色管理',
    'nav.preferences': '偏好设置',
    'nav.k8sManagement': 'K8s管理',
    'nav.k8sClusterManagement': 'K8s集群管理',
    'nav.securityManagement': '安全管理',
    'nav.authorization': '授权',
    'nav.audit': '审计',
    'nav.policyManagement': '策略管理',
    'nav.configInspection': '配置巡检',
    'nav.securityMonitoring': '安全监控',
    'nav.logout': '登出',
    'nav.searchPlaceholder': '请输入搜索内容',
    
    // 偏好设置
    'preferences.title': '偏好设置',
    'preferences.language': '语言设置',
    'preferences.languageDesc': '选择界面显示语言',
    'preferences.theme': '主题设置',
    'preferences.themeDesc': '选择界面主题样式',
    'preferences.themeLight': '浅色',
    'preferences.themeDark': '深色',
    'preferences.themeAuto': '自动',
    'preferences.saveSettings': '保存设置',
    'preferences.saving': '保存中...',
    'preferences.saved': '偏好设置已保存',
    
    // Dashboard
    'dashboard.userInfo': '用户信息',
    'dashboard.viewGitHub': '查看GitHub主页 →',
    
    // 用户管理
    'users.title': '用户管理',
    'users.addUser': '添加用户',
    'users.editUser': '编辑用户',
    'users.username': '用户名',
    'users.email': '邮箱',
    'users.password': '密码',
    'users.name': '姓名',
    'users.role': '角色',
    'users.status': '状态',
    'users.createdAt': '创建时间',
    'users.updatedAt': '更新时间',
    'users.active': '激活',
    'users.inactive': '未激活',
    'users.isActive': '激活状态',
    'users.create': '创建',
    'users.createSuccess': '用户创建成功',
    'users.createFailed': '用户创建失败',
    'users.updateSuccess': '用户更新成功',
    'users.updateFailed': '用户更新失败',
    'users.deleteSuccess': '用户删除成功',
    'users.deleteFailed': '用户删除失败',
    'users.confirmDelete': '确定要删除这个用户吗？',
    'users.noUsers': '暂无用户数据',
    'users.selectRole': '请选择角色',
    'users.usernamePlaceholder': '请输入用户名',
    'users.emailPlaceholder': '请输入邮箱',
    'users.passwordPlaceholder': '请输入密码（至少6位）',
    'users.passwordPlaceholderEdit': '留空则不修改密码',
    'users.passwordHint': '留空则不修改密码',
    'users.namePlaceholder': '请输入姓名',
    
    // 角色管理
    'roles.title': '角色管理',
    
    // 登录
    'login.title': 'DevOps自动化运维平台',
    'login.subtitle': '智能化运维管理，提升工作效率',
    'login.username': '用户名',
    'login.password': '密码',
    'login.submit': '登录',
    'login.error': '账号或密码错误',
    
    // 平台名称
    'platform.name': 'DevOps平台',
    
    // K8s管理
    'k8s.title': 'K8s集群管理',
    'k8s.addCluster': '添加集群',
    'k8s.editCluster': '编辑集群',
    'k8s.name': '集群名称',
    'k8s.type': '集群类型',
    'k8s.typeLocal': '本地部署',
    'k8s.typeAliyun': '阿里云',
    'k8s.typeTencent': '腾讯云',
    'k8s.typeMobile': '移动云',
    'k8s.apiServer': 'API Server',
    'k8s.config': 'Kubeconfig',
    'k8s.configPlaceholder': '请粘贴Kubeconfig内容...',
    'k8s.description': '描述',
    'k8s.status': '状态',
    'k8s.createdAt': '创建时间',
    'k8s.testConnection': '测试连接',
    'k8s.noClusters': '暂无集群',
    'k8s.fetchFailed': '获取集群列表失败',
    'k8s.createSuccess': '集群创建成功',
    'k8s.updateSuccess': '集群更新成功',
    'k8s.deleteSuccess': '集群删除成功',
    'k8s.deleteFailed': '集群删除失败',
    'k8s.operationFailed': '操作失败',
    'k8s.connectionSuccess': '连接成功',
    'k8s.connectionFailed': '连接失败',
    'k8s.testFailed': '测试连接失败',
    'k8s.confirmDelete': '确定要删除这个集群吗？',
    'k8s.viewDetails': '查看详情',
    'k8s.clusterDetail': '集群详情',
    'k8s.clusterInfo': '集群信息',
    'k8s.nodes': '节点',
    'k8s.namespaces': '命名空间',
    'k8s.basicInfo': '基本信息',
    'k8s.configuration': '配置信息',
    'k8s.versionInfo': '版本信息',
    'k8s.resources': '资源统计',
    'k8s.k8sVersion': 'K8s版本',
    'k8s.platform': '平台',
    'k8s.nodeCount': '节点数量',
    'k8s.namespaceCount': '命名空间数量',
    'k8s.nodeName': '节点名称',
    'k8s.roles': '角色',
    'k8s.version': '版本',
    'k8s.os': '操作系统',
    'k8s.cpu': 'CPU',
    'k8s.memory': '内存',
    'k8s.pods': '容器组',
    'k8s.namespaceName': '命名空间名称',
    'k8s.labels': '标签',
    'k8s.noNodes': '暂无节点',
    'k8s.noNamespaces': '暂无命名空间',
    'k8s.namespacesAndQuota': '命名空间与配额',
    'k8s.searchPlaceholder': '请输入',
    'k8s.resourceQuotaAndLimits': '资源配额与限制',
    'k8s.quotaInfoBanner': '对命名空间设置CPU/内存配额(Resource Quota)后,创建容器组时,必须指定CPU/内存资源限制,或者命名空间配置默认资源限制(LimitRange),详情请参见:Resource Quotas.',
    'k8s.resourceQuota': 'Resource Quota',
    'k8s.defaultResourceLimits': '默认资源限制 (Limit Range)',
    'k8s.computeResourceLimits': '计算资源限制',
    'k8s.storageResourceLimits': '存储资源限制',
    'k8s.otherResourceLimits': '其他资源限制',
    'k8s.resourceLimit': '资源限制',
    'k8s.resourceRequest': '资源申请',
    'k8s.cpuLimit': 'CPU限制',
    'k8s.memoryLimit': '内存限制',
    'k8s.cpuRequest': 'CPU请求',
    'k8s.memoryRequest': '内存请求',
    'k8s.exclusiveGpuLimit': '独占GPU限制',
    'k8s.sharedGpuMemoryLimit': '共享GPU显存限制',
    'k8s.storageClaimQuantity': '存储声明数量',
    'k8s.storageSpace': '存储空间',
    'k8s.configFileQuantity': '配置文件数量',
    'k8s.containerGroupQuantity': '容器组数量',
    'k8s.serviceQuantity': '服务数量',
    'k8s.loadBalancerServiceQuantity': '负载均衡型服务数量',
    'k8s.secretQuantity': '保密字典数量',
    'k8s.maxUsage': '最大使用量',
    'k8s.noLimit': '无限制',
    'k8s.updateQuotaSuccess': '资源配额更新成功',
    'k8s.updateQuotaFailed': '资源配额更新失败',
    'k8s.createNamespace': '创建命名空间',
    'k8s.namespaceNamePlaceholder': '请输入命名空间名称',
    'k8s.namespaceNameRule': '长度为1~63个字符,只能包含数字、小写字母和中划线(-),首尾只能是字母或数字',
    'k8s.namespaceNameRequired': '请输入命名空间名称',
    'k8s.namespaceNameInvalid': '命名空间名称格式不正确',
    'k8s.deletionProtection': '删除保护',
    'k8s.enableDeletionProtection': '是否开启删除保护',
    'k8s.namespaceTags': '命名空间标签',
    'k8s.variableName': '变量名称',
    'k8s.variableValue': '变量值',
    'k8s.addNamespaceTag': '命名空间标签',
    'k8s.createNamespaceSuccess': '命名空间创建成功',
    'k8s.createNamespaceFailed': '命名空间创建失败',
    'k8s.editNamespace': '编辑命名空间',
    'k8s.editNamespaceSuccess': '命名空间编辑成功',
    'k8s.editNamespaceFailed': '命名空间编辑失败',
    'k8s.monitoring': '监控',
    'k8s.yamlEdit': 'YAML 编辑',
    'k8s.deleteNamespaceSuccess': '命名空间删除成功',
    'k8s.deleteNamespaceFailed': '命名空间删除失败',
    'k8s.enableDeletionProtectionSuccess': '已开启删除保护',
    'k8s.disableDeletionProtectionSuccess': '已关闭删除保护',
    'k8s.toggleDeletionProtectionFailed': '切换删除保护失败',
    'k8s.confirmDeleteNamespace': '确定要删除此命名空间吗？',
    'k8s.create': '创建',
    'k8s.applicationName': '应用名称',
    'k8s.applicationNamePlaceholder': '请输入应用名称',
    'k8s.applicationNameRule': '名称为1-63个字符,可包含数字、小写英文字以及短划线(-),且不能以短划线(-)开头',
    'k8s.replicas': '副本数量',
    'k8s.timeZoneSync': '容器与节点使用相同时区',
    'k8s.imageName': '镜像名称',
    'k8s.imageNamePlaceholder': '请输入镜像地址,版本号以冒号分割。例如:nginx:latest',
    'k8s.selectImage': '选择镜像',
    'k8s.imagePullPolicy': '镜像拉取策略',
    'k8s.setImageSecret': '设置镜像密钥',
    'k8s.resourceLimits': '资源限制',
    'k8s.resourceRequests': '所需资源',
    'k8s.cpuExample': '如: 0.5 Core',
    'k8s.memoryExample': '如: 512 MiB',
    'k8s.ephemeralStorageExample': '如: 2 GiB',
    'k8s.gpuResourceLimits': 'GPU资源限制',
    'k8s.dontUseGpu': '不使用',
    'k8s.exclusiveGpu': '独占GPU',
    'k8s.sharedGpu': '共享GPU',
    'k8s.containerStartup': '容器启动项',
    'k8s.privilegedContainer': '设置为特权容器',
    'k8s.initContainer': '设置为初始化容器',
    'k8s.ports': '端口',
    'k8s.portName': '端口名称',
    'k8s.envVars': '环境变量',
    'k8s.hpaEnabled': '指标伸缩',
    'k8s.cronHpaEnabled': '定时伸缩',
    'k8s.upgradeStrategy': '升级方式',
    'k8s.podLabels': 'Pod标签',
    'k8s.value': '值',
    'k8s.nameAndNamespaceRequired': '请填写应用名称和命名空间',
    'k8s.imageRequired': '请至少为一个容器设置镜像',
    'k8s.createDeploymentSuccess': '创建成功',
    'k8s.createDeploymentFailed': '创建失败',
    'k8s.deploymentCreatedMessage': 'Deployment 已成功创建',
    'k8s.ready': '就绪',
    'k8s.nodePool': '节点池',
    'k8s.node': '节点',
    'k8s.componentManagement': '组件管理',
    'k8s.application': '应用',
    'k8s.inspectionAndDiagnosis': '巡检和诊断',
    'k8s.operationsManagement': '运维管理',
    'k8s.costSuite': '成本套件',
    'k8s.fetchInfoFailed': '获取集群信息失败',
    'k8s.fetchNodesFailed': '获取节点列表失败',
    'k8s.fetchNamespacesFailed': '获取命名空间列表失败',
    'k8s.viewPods': '查看Pod',
    'k8s.podsInNamespace': '命名空间 {namespace} 的Pod',
    'k8s.podName': 'Pod名称',
    'k8s.restarts': '重启次数',
    'k8s.age': '运行时间',
    'k8s.restart': '重启',
    'k8s.confirmRestartPod': '确定要重启Pod {podName}吗？',
    'k8s.restartPodSuccess': 'Pod重启成功',
    'k8s.restartPodFailed': 'Pod重启失败',
    'k8s.fetchPodsFailed': '获取Pod列表失败',
    'k8s.noPods': '暂无Pod',
    'k8s.noPodsInNamespace': '该命名空间下暂无Pod',
    'k8s.editYaml': '编辑YAML',
    'k8s.fetchYamlFailed': '获取YAML失败',
    'k8s.updateYamlSuccess': 'YAML更新成功',
    'k8s.updateYamlFailed': 'YAML更新失败',
    'k8s.searchPods': '搜索Pod（名称、状态、节点...）',
    'k8s.noPodsFound': '未找到匹配的Pod',
    'common.more': '更多',
    'k8s.namespace': '命名空间',
    'k8s.containers': '容器数量',
    'k8s.images': '镜像',
    'k8s.updatedAt': '更新时间',
    'k8s.podDetail': 'Pod详情',
    'k8s.detail': '详情',
    'k8s.logs': '日志',
    'k8s.editLabels': '编辑标签',
    'k8s.editAnnotations': '编辑注解',
    'k8s.labelKey': '标签键',
    'k8s.labelValue': '标签值',
    'k8s.annotationKey': '注解键',
    'k8s.annotationValue': '注解值',
    'k8s.addLabel': '添加标签',
    'k8s.addAnnotation': '添加注解',
    'k8s.podLogs': 'Pod日志',
    'k8s.noLogs': '暂无日志',
    'k8s.fetchDetailFailed': '获取Pod详情失败',
    'k8s.fetchLogsFailed': '获取Pod日志失败',
    'k8s.deletePodSuccess': 'Pod删除成功',
    'k8s.deletePodFailed': 'Pod删除失败',
    'k8s.confirmDeletePod': '确定要删除Pod {podName}吗？',
    'k8s.updateLabelsSuccess': '标签更新成功',
    'k8s.updateLabelsFailed': '标签更新失败',
    'k8s.updateAnnotationsSuccess': '注解更新成功',
    'k8s.updateAnnotationsFailed': '注解更新失败',
    'k8s.yamlEditWarning': '⚠️ Pod更新限制',
    'k8s.yamlEditWarningDesc': 'Kubernetes限制Pod只能修改以下字段：容器镜像、初始化容器镜像、activeDeadlineSeconds、tolerations（仅添加）、terminationGracePeriodSeconds（特定条件）。资源限制（CPU/内存）等字段需要通过Deployment或StatefulSet进行修改。',
    'k8s.nodeManagement': '节点管理',
    'k8s.workloads': '工作负载',
    'k8s.network': '网络',
    'k8s.configManagement': '配置管理',
    'k8s.storage': '存储',
    'k8s.service': '服务',
    'k8s.serviceName': '服务名称',
    'k8s.serviceType': '服务类型',
    'k8s.clusterIP': 'Cluster IP',
    'k8s.noServices': '暂无服务',
    'k8s.configMaps': 'ConfigMaps',
    'k8s.configMapName': 'ConfigMap名称',
    'k8s.dataKeys': '数据键',
    'k8s.noConfigMaps': '暂无ConfigMap',
    'k8s.secrets': 'Secrets',
    'k8s.secretName': 'Secret名称',
    'k8s.secretType': 'Secret类型',
    'k8s.noSecrets': '暂无Secret',
    'k8s.pvcName': 'PVC名称',
    'k8s.capacity': '容量',
    'k8s.accessModes': '访问模式',
    'k8s.storageClass': '存储类',
    'k8s.noPVCs': '暂无PVC',
    'k8s.fetchWorkloadsFailed': '获取工作负载失败',
    'k8s.fetchServicesFailed': '获取服务列表失败',
    'k8s.fetchConfigMapsFailed': '获取ConfigMap列表失败',
    'k8s.fetchSecretsFailed': '获取Secret列表失败',
    'k8s.fetchPVCsFailed': '获取PVC列表失败',
    'k8s.deployments': '无状态',
    'k8s.stateless': '无状态',
    'k8s.statefulsets': '有状态',
    'k8s.stateful': '有状态',
    'k8s.daemonsets': '守护进程集',
    'k8s.jobs': '任务',
    'k8s.cronjobs': '定时任务',
    'k8s.customResources': '自定义资源',
    'k8s.deploymentName': 'Deployment名称',
    'k8s.statefulSetName': 'StatefulSet名称',
    'k8s.daemonSetName': 'DaemonSet名称',
    'k8s.jobName': 'Job名称',
    'k8s.cronJobName': 'CronJob名称',
    'k8s.readyReplicas': '就绪副本',
    'k8s.desired': '期望',
    'k8s.current': '当前',
    'k8s.completions': '完成数',
    'k8s.succeeded': '成功',
    'k8s.active': '活跃',
    'k8s.failed': '失败',
    'k8s.schedule': '调度',
    'k8s.lastScheduleTime': '上次调度时间',
    'k8s.suspend': '暂停',
    'k8s.noDeployments': '暂无Deployment',
    'k8s.noStatefulSets': '暂无StatefulSet',
    'k8s.noDaemonSets': '暂无DaemonSet',
    'k8s.noJobs': '暂无Job',
    'k8s.noCronJobs': '暂无CronJob',
    'k8s.fetchDeploymentsFailed': '获取Deployment列表失败',
    'k8s.fetchStatefulSetsFailed': '获取StatefulSet列表失败',
    'k8s.fetchDaemonSetsFailed': '获取DaemonSet列表失败',
    'k8s.fetchJobsFailed': '获取Job列表失败',
    'k8s.fetchCronJobsFailed': '获取CronJob列表失败',
    'k8s.fetchIngressesFailed': '获取Ingress列表失败',
    'k8s.noIngresses': '暂无Ingress',
    'k8s.customResourcesComingSoon': '自定义资源功能即将推出',
    'k8s.eventsComingSoon': '事件功能即将推出',
    'k8s.storageComingSoon': '存储功能即将推出',
    'k8s.monitoringComingSoon': '监控功能即将推出',
    'common.yes': '是',
    'common.no': '否',
    'k8s.allNamespaces': '全部命名空间',
    'k8s.searchWorkloads': '搜索工作负载（名称、命名空间...）',
    'k8s.noWorkloadsFound': '未找到匹配的工作负载',
    'k8s.createFromImage': '使用镜像创建',
    'k8s.createFromYaml': '使用YAML创建资源',
    'k8s.yamlPlaceholder': '请粘贴YAML内容...\n\n示例:\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: my-app\n  namespace: default\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: my-app\n  template:\n    metadata:\n      labels:\n        app: my-app\n    spec:\n      containers:\n      - name: app\n        image: nginx:latest',
    'k8s.yamlRequired': '请输入YAML内容',
    'k8s.nameAndImageRequired': '请输入名称和镜像',
    'k8s.createWorkloadSuccess': '工作负载创建成功',
    'k8s.createWorkloadFailed': '工作负载创建失败',
    'k8s.workloadName': '工作负载名称',
    'k8s.workloadNamePlaceholder': '请输入工作负载名称',
    'k8s.image': '镜像',
    'k8s.containerPort': '容器端口',
    'k8s.pleaseEnter': '请输入',
    'k8s.tags': '标签',
    'k8s.podCount': '容器组数量',
    'k8s.scale': '伸缩',
    'k8s.more': '更多',
    'k8s.selector': '选择器',
    'k8s.annotations': '注解',
    'k8s.strategy': '策略',
    'k8s.maxSurge': '超过期望的Pod数量',
    'k8s.maxUnavailable': '不可用Pod最大数量',
    'k8s.unit': '个',
    'k8s.updated': '已更新',
    'k8s.available': '可用',
    'k8s.expandStatus': '展开现状详情',
    'k8s.rollingUpdateStrategy': '滚动升级策略',
    'k8s.containerGroup': '容器组',
    'k8s.accessMethod': '访问方式',
    'k8s.events': '事件',
    'k8s.containerScaling': '容器伸缩',
    'k8s.historyVersions': '历史版本',
    'k8s.podIP': 'Pod IP',
    'k8s.terminal': '终端',
    'k8s.restartCount': '重启次数',
    'k8s.showAll': '显示全部',
    'k8s.featureComingSoon': '功能即将推出',
    'k8s.comingSoon': '功能即将推出',
    'k8s.costInsights': '成本洞察',
    'k8s.costInsight': '成本洞察',
    'k8s.triggers': '触发器',
    'k8s.scaleDeployment': '请输入副本数量',
    'k8s.invalidReplicas': '无效的副本数量',
    'k8s.scaleSuccess': '伸缩成功',
    'k8s.scaleFailed': '伸缩失败',
    'k8s.costOverview': '成本概览',
    'k8s.totalCost': '总成本',
    'k8s.cpuCost': 'CPU成本',
    'k8s.memoryCost': '内存成本',
    'k8s.storageCost': '存储成本',
    'k8s.networkCost': '网络成本',
    'k8s.resourceUsage': '资源使用',
    'k8s.cpuUsage': 'CPU使用',
    'k8s.memoryUsage': '内存使用',
    'k8s.storageUsage': '存储使用',
    'k8s.costBreakdown': '成本明细',
    'k8s.dailyCost': '日均成本',
    'k8s.monthlyCost': '月均成本',
    'k8s.yearlyCost': '年均成本',
    'k8s.costInfoNotAvailable': '成本信息暂不可用',
    'k8s.imagePlaceholder': '请输入镜像地址',
    'k8s.key': '键',
    'k8s.replicasHint': '副本数量可以设置为0，设置为0将停止所有Pod',
    'k8s.updateDeploymentFailed': '更新Deployment失败',
    'k8s.scaleDeploymentFailed': '伸缩Deployment失败',
    'k8s.intelligentOptimization': '智能优化',
    'k8s.redeploy': '重新部署',
    'k8s.elasticScaling': '弹性伸缩',
    'k8s.nodeAffinity': '节点亲和性',
    'k8s.schedulingToleration': '调度容忍',
    'k8s.resourceProfile': '资源画像',
    'k8s.cloneCreate': '复制创建',
    'k8s.rollback': '回滚',
    'k8s.confirmRedeploy': '确定要重新部署此Deployment吗？',
    'k8s.confirmDeleteDeployment': '确定要删除此Deployment吗？此操作不可恢复。',
    'k8s.redeployFailed': '重新部署失败',
    'k8s.deleteDeploymentFailed': '删除Deployment失败',
    'k8s.confirmDeleteStatefulSet': '确定要删除此StatefulSet吗？此操作不可恢复。',
    'k8s.confirmDeleteDaemonSet': '确定要删除此DaemonSet吗？此操作不可恢复。',
    'k8s.confirmDeleteJob': '确定要删除此Job吗？此操作不可恢复。',
    'k8s.confirmDeleteCronJob': '确定要删除此CronJob吗？此操作不可恢复。',
    'k8s.deleteStatefulSetFailed': '删除StatefulSet失败',
    'k8s.updateStatefulSetFailed': '更新StatefulSet失败',
    'k8s.scaleStatefulSetFailed': '伸缩StatefulSet失败',
  },
  'en-US': {
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.loading': 'Loading...',
    'common.saveSuccess': 'Saved successfully',
    'common.saveFailed': 'Save failed',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.actions': 'Actions',
    'common.back': 'Back',
    'common.clear': 'Clear',
    'common.create': 'Create',
    'common.refresh': 'Refresh',
    
    // Pagination
    'pagination.showing': 'Showing',
    'pagination.of': 'of',
    'pagination.items': 'items',
    'pagination.firstPage': 'First Page',
    'pagination.previousPage': 'Previous Page',
    'pagination.nextPage': 'Next Page',
    'pagination.lastPage': 'Last Page',
    'pagination.itemsPerPage': 'Items per page',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.menuManagement': 'Menu Management',
    'nav.userManagement': 'User Management',
    'nav.roleManagement': 'Role Management',
    'nav.preferences': 'Preferences',
    'nav.k8sManagement': 'K8s Management',
    'nav.k8sClusterManagement': 'K8s Cluster Management',
    'nav.securityManagement': 'Security Management',
    'nav.authorization': 'Authorization',
    'nav.audit': 'Audit',
    'nav.searchPlaceholder': 'Please enter search content',
    'nav.policyManagement': 'Policy Management',
    'nav.configInspection': 'Config Inspection',
    'nav.securityMonitoring': 'Security Monitoring',
    'nav.logout': 'Logout',
    
    // Preferences
    'preferences.title': 'Preferences',
    'preferences.language': 'Language',
    'preferences.languageDesc': 'Select interface display language',
    'preferences.theme': 'Theme',
    'preferences.themeDesc': 'Select interface theme style',
    'preferences.themeLight': 'Light',
    'preferences.themeDark': 'Dark',
    'preferences.themeAuto': 'Auto',
    'preferences.saveSettings': 'Save Settings',
    'preferences.saving': 'Saving...',
    'preferences.saved': 'Preferences saved',
    
    // Dashboard
    'dashboard.userInfo': 'User Information',
    'dashboard.viewGitHub': 'View GitHub Profile →',
    
    // User Management
    'users.title': 'User Management',
    'users.addUser': 'Add User',
    'users.editUser': 'Edit User',
    'users.username': 'Username',
    'users.email': 'Email',
    'users.password': 'Password',
    'users.name': 'Name',
    'users.role': 'Role',
    'users.status': 'Status',
    'users.createdAt': 'Created At',
    'users.updatedAt': 'Updated At',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.isActive': 'Active Status',
    'users.create': 'Create',
    'users.createSuccess': 'User created successfully',
    'users.createFailed': 'Failed to create user',
    'users.updateSuccess': 'User updated successfully',
    'users.updateFailed': 'Failed to update user',
    'users.deleteSuccess': 'User deleted successfully',
    'users.deleteFailed': 'Failed to delete user',
    'users.confirmDelete': 'Are you sure you want to delete this user?',
    'users.noUsers': 'No users',
    'users.selectRole': 'Select Role',
    'users.usernamePlaceholder': 'Enter username',
    'users.emailPlaceholder': 'Enter email',
    'users.passwordPlaceholder': 'Enter password (min 6 characters)',
    'users.passwordPlaceholderEdit': 'Leave blank to keep current password',
    'users.passwordHint': 'Leave blank to keep current password',
    'users.namePlaceholder': 'Enter name',
    
    // Role Management
    'roles.title': 'Role Management',
    
    // Login
    'login.title': 'DevOps Automation Operations Platform',
    'login.subtitle': 'Intelligent operations management to improve work efficiency',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.submit': 'Login',
    'login.error': 'Invalid username or password',
    
    // Platform name
    'platform.name': 'DevOps Platform',
    
    // K8s Management
    'k8s.title': 'K8s Cluster Management',
    'k8s.addCluster': 'Add Cluster',
    'k8s.editCluster': 'Edit Cluster',
    'k8s.name': 'Cluster Name',
    'k8s.type': 'Cluster Type',
    'k8s.typeLocal': 'Local',
    'k8s.typeAliyun': 'Aliyun',
    'k8s.typeTencent': 'Tencent Cloud',
    'k8s.typeMobile': 'Mobile Cloud',
    'k8s.apiServer': 'API Server',
    'k8s.config': 'Kubeconfig',
    'k8s.configPlaceholder': 'Paste Kubeconfig content here...',
    'k8s.description': 'Description',
    'k8s.status': 'Status',
    'k8s.createdAt': 'Created At',
    'k8s.testConnection': 'Test Connection',
    'k8s.noClusters': 'No clusters',
    'k8s.fetchFailed': 'Failed to fetch clusters',
    'k8s.createSuccess': 'Cluster created successfully',
    'k8s.updateSuccess': 'Cluster updated successfully',
    'k8s.deleteSuccess': 'Cluster deleted successfully',
    'k8s.deleteFailed': 'Failed to delete cluster',
    'k8s.operationFailed': 'Operation failed',
    'k8s.connectionSuccess': 'Connection successful',
    'k8s.connectionFailed': 'Connection failed',
    'k8s.testFailed': 'Test connection failed',
    'k8s.confirmDelete': 'Are you sure you want to delete this cluster?',
    'k8s.viewDetails': 'View Details',
    'k8s.clusterDetail': 'Cluster Detail',
    'k8s.clusterInfo': 'Cluster Info',
    'k8s.nodes': 'Nodes',
    'k8s.namespaces': 'Namespaces',
    'k8s.basicInfo': 'Basic Info',
    'k8s.versionInfo': 'Version Info',
    'k8s.resources': 'Resources',
    'k8s.k8sVersion': 'K8s Version',
    'k8s.platform': 'Platform',
    'k8s.nodeCount': 'Node Count',
    'k8s.namespaceCount': 'Namespace Count',
    'k8s.nodeName': 'Node Name',
    'k8s.roles': 'Roles',
    'k8s.version': 'Version',
    'k8s.os': 'OS',
    'k8s.cpu': 'CPU',
    'k8s.memory': 'Memory',
    'k8s.pods': 'Pods',
    'k8s.namespaceName': 'Namespace Name',
    'k8s.createNamespace': 'Create Namespace',
    'k8s.namespaceNamePlaceholder': 'Please enter namespace name',
    'k8s.namespaceNameRule': 'Length 1-63 characters, can only contain numbers, lowercase letters, and hyphens (-), the beginning and end can only be letters or numbers',
    'k8s.namespaceNameRequired': 'Please enter namespace name',
    'k8s.namespaceNameInvalid': 'Invalid namespace name format',
    'k8s.deletionProtection': 'Deletion Protection',
    'k8s.enableDeletionProtection': 'Whether to enable deletion protection',
    'k8s.namespaceTags': 'Namespace Tags',
    'k8s.variableName': 'Variable Name',
    'k8s.variableValue': 'Variable Value',
    'k8s.addNamespaceTag': 'Namespace Tag',
    'k8s.createNamespaceSuccess': 'Namespace created successfully',
    'k8s.createNamespaceFailed': 'Failed to create namespace',
    'k8s.editNamespace': 'Edit Namespace',
    'k8s.editNamespaceSuccess': 'Namespace updated successfully',
    'k8s.editNamespaceFailed': 'Failed to update namespace',
    'k8s.labels': 'Labels',
    'k8s.noNodes': 'No nodes',
    'k8s.noNamespaces': 'No namespaces',
    'k8s.fetchInfoFailed': 'Failed to fetch cluster info',
    'k8s.fetchNodesFailed': 'Failed to fetch nodes',
    'k8s.fetchNamespacesFailed': 'Failed to fetch namespaces',
    'k8s.viewPods': 'View Pods',
    'k8s.podsInNamespace': 'Pods in namespace {namespace}',
    'k8s.podName': 'Pod Name',
    'k8s.ready': 'Ready',
    'k8s.restarts': 'Restarts',
    'k8s.age': 'Age',
    'k8s.restart': 'Restart',
    'k8s.confirmRestartPod': 'Are you sure you want to restart pod {podName}?',
    'k8s.restartPodSuccess': 'Pod restarted successfully',
    'k8s.restartPodFailed': 'Failed to restart pod',
    'k8s.fetchPodsFailed': 'Failed to fetch pods',
    'k8s.noPods': 'No pods',
    'k8s.editYaml': 'Edit YAML',
    'k8s.fetchYamlFailed': 'Failed to fetch YAML',
    'k8s.updateYamlSuccess': 'YAML updated successfully',
    'k8s.updateYamlFailed': 'Failed to update YAML',
    'k8s.searchPods': 'Search pods (name, status, node...)',
    'k8s.noPodsFound': 'No pods found',
    'common.more': 'More',
    'k8s.namespace': 'Namespace',
    'k8s.resourceQuotaAndLimits': 'Resource Quota and Limits',
    'k8s.quotaInfoBanner': 'After setting CPU/memory quotas (Resource Quota) for a namespace, when creating container groups, you must specify CPU/memory resource limits, or configure default resource limits (LimitRange) for the namespace. For details, please refer to: Resource Quotas.',
    'k8s.resourceQuota': 'Resource Quota',
    'k8s.defaultResourceLimits': 'Default Resource Limits (Limit Range)',
    'k8s.computeResourceLimits': 'Compute Resource Limits',
    'k8s.storageResourceLimits': 'Storage Resource Limits',
    'k8s.otherResourceLimits': 'Other Resource Limits',
    'k8s.resourceLimit': 'Resource Limit',
    'k8s.resourceRequest': 'Resource Request',
    'k8s.cpuLimit': 'CPU Limit',
    'k8s.memoryLimit': 'Memory Limit',
    'k8s.cpuRequest': 'CPU Request',
    'k8s.memoryRequest': 'Memory Request',
    'k8s.exclusiveGpuLimit': 'Exclusive GPU Limit',
    'k8s.sharedGpuMemoryLimit': 'Shared GPU Memory Limit',
    'k8s.storageClaimQuantity': 'Storage Claim Quantity',
    'k8s.storageSpace': 'Storage Space',
    'k8s.configFileQuantity': 'Config File Quantity',
    'k8s.containerGroupQuantity': 'Container Group Quantity',
    'k8s.serviceQuantity': 'Service Quantity',
    'k8s.loadBalancerServiceQuantity': 'Load Balancer Service Quantity',
    'k8s.secretQuantity': 'Secret Quantity',
    'k8s.maxUsage': 'Max usage',
    'k8s.noLimit': 'No limit',
    'k8s.updateQuotaSuccess': 'Resource quota updated successfully',
    'k8s.updateQuotaFailed': 'Failed to update resource quota',
    'k8s.monitoring': 'Monitoring',
    'k8s.yamlEdit': 'YAML Edit',
    'k8s.deleteNamespaceSuccess': 'Namespace deleted successfully',
    'k8s.deleteNamespaceFailed': 'Failed to delete namespace',
    'k8s.enableDeletionProtectionSuccess': 'Deletion protection enabled',
    'k8s.disableDeletionProtectionSuccess': 'Deletion protection disabled',
    'k8s.toggleDeletionProtectionFailed': 'Failed to toggle deletion protection',
    'k8s.confirmDeleteNamespace': 'Are you sure you want to delete this namespace?',
    'k8s.containers': 'Containers',
    'k8s.images': 'Images',
    'k8s.updatedAt': 'Updated At',
    'k8s.podDetail': 'Pod Detail',
    'k8s.detail': 'Detail',
    'k8s.logs': 'Logs',
    'k8s.editLabels': 'Edit Labels',
    'k8s.editAnnotations': 'Edit Annotations',
    'k8s.labelKey': 'Label Key',
    'k8s.labelValue': 'Label Value',
    'k8s.annotationKey': 'Annotation Key',
    'k8s.annotationValue': 'Annotation Value',
    'k8s.addLabel': 'Add Label',
    'k8s.addAnnotation': 'Add Annotation',
    'k8s.podLogs': 'Pod Logs',
    'k8s.noLogs': 'No logs',
    'k8s.fetchDetailFailed': 'Failed to fetch pod detail',
    'k8s.fetchLogsFailed': 'Failed to fetch pod logs',
    'k8s.deletePodSuccess': 'Pod deleted successfully',
    'k8s.deletePodFailed': 'Failed to delete pod',
    'k8s.confirmDeletePod': 'Are you sure you want to delete pod {podName}?',
    'k8s.updateLabelsSuccess': 'Labels updated successfully',
    'k8s.updateLabelsFailed': 'Failed to update labels',
    'k8s.updateAnnotationsSuccess': 'Annotations updated successfully',
    'k8s.updateAnnotationsFailed': 'Failed to update annotations',
    'k8s.yamlEditWarning': '⚠️ Pod Update Restrictions',
    'k8s.yamlEditWarningDesc': 'Kubernetes only allows updating the following Pod fields: container images, init container images, activeDeadlineSeconds, tolerations (additions only), terminationGracePeriodSeconds (specific conditions). Resource limits (CPU/memory) must be modified through Deployment or StatefulSet.',
    'k8s.nodeManagement': 'Node Management',
    'k8s.namespacesAndQuota': 'Namespaces & Quota',
    'k8s.workloads': 'Workloads',
    'k8s.network': 'Network',
    'k8s.configManagement': 'Config Management',
    'k8s.storage': 'Storage',
    'k8s.service': 'Service',
    'k8s.serviceName': 'Service Name',
    'k8s.serviceType': 'Service Type',
    'k8s.clusterIP': 'Cluster IP',
    'k8s.ports': 'Ports',
    'k8s.noServices': 'No services',
    'k8s.configMaps': 'ConfigMaps',
    'k8s.configMapName': 'ConfigMap Name',
    'k8s.dataKeys': 'Data Keys',
    'k8s.noConfigMaps': 'No ConfigMaps',
    'k8s.secrets': 'Secrets',
    'k8s.secretName': 'Secret Name',
    'k8s.secretType': 'Secret Type',
    'k8s.noSecrets': 'No secrets',
    'k8s.pvcName': 'PVC Name',
    'k8s.capacity': 'Capacity',
    'k8s.accessModes': 'Access Modes',
    'k8s.storageClass': 'Storage Class',
    'k8s.noPVCs': 'No PVCs',
    'k8s.fetchWorkloadsFailed': 'Failed to fetch workloads',
    'k8s.fetchServicesFailed': 'Failed to fetch services',
    'k8s.fetchConfigMapsFailed': 'Failed to fetch ConfigMaps',
    'k8s.fetchSecretsFailed': 'Failed to fetch secrets',
    'k8s.fetchPVCsFailed': 'Failed to fetch PVCs',
    'k8s.deployments': 'Deployments',
    'k8s.stateless': 'Stateless',
    'k8s.statefulsets': 'StatefulSets',
    'k8s.stateful': 'Stateful',
    'k8s.daemonsets': 'DaemonSets',
    'k8s.jobs': 'Jobs',
    'k8s.cronjobs': 'CronJobs',
    'k8s.customResources': 'Custom Resources',
    'k8s.nodePool': 'Node Pool',
    'k8s.node': 'Node',
    'k8s.componentManagement': 'Component Management',
    'k8s.application': 'Application',
    'k8s.inspectionAndDiagnosis': 'Inspection and Diagnosis',
    'k8s.operationsManagement': 'Operations Management',
    'k8s.costSuite': 'Cost Suite',
    'k8s.deploymentName': 'Deployment Name',
    'k8s.statefulSetName': 'StatefulSet Name',
    'k8s.daemonSetName': 'DaemonSet Name',
    'k8s.jobName': 'Job Name',
    'k8s.cronJobName': 'CronJob Name',
    'k8s.replicas': 'Replicas',
    'k8s.readyReplicas': 'Ready Replicas',
    'k8s.desired': 'Desired',
    'k8s.current': 'Current',
    'k8s.completions': 'Completions',
    'k8s.succeeded': 'Succeeded',
    'k8s.active': 'Active',
    'k8s.failed': 'Failed',
    'k8s.schedule': 'Schedule',
    'k8s.lastScheduleTime': 'Last Schedule Time',
    'k8s.suspend': 'Suspend',
    'k8s.noDeployments': 'No deployments',
    'k8s.noStatefulSets': 'No statefulsets',
    'k8s.noDaemonSets': 'No daemonsets',
    'k8s.noJobs': 'No jobs',
    'k8s.noCronJobs': 'No cronjobs',
    'k8s.fetchIngressesFailed': 'Failed to fetch ingresses',
    'k8s.noIngresses': 'No ingresses',
    'k8s.fetchDeploymentsFailed': 'Failed to fetch deployments',
    'k8s.fetchStatefulSetsFailed': 'Failed to fetch statefulsets',
    'k8s.fetchDaemonSetsFailed': 'Failed to fetch daemonsets',
    'k8s.fetchJobsFailed': 'Failed to fetch jobs',
    'k8s.fetchCronJobsFailed': 'Failed to fetch cronjobs',
    'k8s.customResourcesComingSoon': 'Custom resources feature coming soon',
    'k8s.eventsComingSoon': 'Events feature coming soon',
    'k8s.storageComingSoon': 'Storage feature coming soon',
    'k8s.monitoringComingSoon': 'Monitoring feature coming soon',
    'common.yes': 'Yes',
    'common.no': 'No',
    'k8s.allNamespaces': 'All Namespaces',
    'k8s.searchWorkloads': 'Search workloads (name, namespace...)',
    'k8s.noWorkloadsFound': 'No workloads found',
    'k8s.createFromImage': 'Create with Image',
    'k8s.createFromYaml': 'Create Resource with YAML',
    'k8s.yamlPlaceholder': 'Paste YAML content here...\n\nExample:\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: my-app\n  namespace: default\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: my-app\n  template:\n    metadata:\n      labels:\n        app: my-app\n    spec:\n      containers:\n      - name: app\n        image: nginx:latest',
    'k8s.yamlRequired': 'Please enter YAML content',
    'k8s.nameAndImageRequired': 'Please enter name and image',
    'k8s.createWorkloadSuccess': 'Workload created successfully',
    'k8s.createWorkloadFailed': 'Failed to create workload',
    'k8s.workloadName': 'Workload Name',
    'k8s.workloadNamePlaceholder': 'Enter workload name',
    'k8s.image': 'Image',
    'k8s.containerPort': 'Container Port',
    'k8s.pleaseEnter': 'Please enter',
    'k8s.tags': 'Tags',
    'k8s.podCount': 'Pod Count',
    'k8s.scale': 'Scale',
    'k8s.more': 'More',
    'k8s.selector': 'Selector',
    'k8s.annotations': 'Annotations',
    'k8s.strategy': 'Strategy',
    'k8s.maxSurge': 'Max Surge',
    'k8s.maxUnavailable': 'Max Unavailable',
    'k8s.unit': '',
    'k8s.updated': 'Updated',
    'k8s.available': 'Available',
    'k8s.expandStatus': 'Expand Status Details',
    'k8s.rollingUpdateStrategy': 'Rolling Update Strategy',
    'k8s.containerGroup': 'Container Group',
    'k8s.accessMethod': 'Access Method',
    'k8s.events': 'Events',
    'k8s.containerScaling': 'Container Scaling',
    'k8s.historyVersions': 'History Versions',
    'k8s.podIP': 'Pod IP',
    'k8s.terminal': 'Terminal',
    'k8s.restartCount': 'Restart Count',
    'k8s.showAll': 'Show All',
    'k8s.featureComingSoon': 'Feature coming soon',
    'k8s.comingSoon': 'Coming Soon',
    'k8s.costInsights': 'Cost Insights',
    'k8s.costInsight': 'Cost Insight',
    'k8s.triggers': 'Triggers',
    'k8s.scaleDeployment': 'Enter replica count',
    'k8s.invalidReplicas': 'Invalid replica count',
    'k8s.scaleSuccess': 'Scale successful',
    'k8s.scaleFailed': 'Scale failed',
    'k8s.costOverview': 'Cost Overview',
    'k8s.totalCost': 'Total Cost',
    'k8s.cpuCost': 'CPU Cost',
    'k8s.memoryCost': 'Memory Cost',
    'k8s.storageCost': 'Storage Cost',
    'k8s.networkCost': 'Network Cost',
    'k8s.resourceUsage': 'Resource Usage',
    'k8s.cpuUsage': 'CPU Usage',
    'k8s.memoryUsage': 'Memory Usage',
    'k8s.storageUsage': 'Storage Usage',
    'k8s.costBreakdown': 'Cost Breakdown',
    'k8s.dailyCost': 'Daily Cost',
    'k8s.monthlyCost': 'Monthly Cost',
    'k8s.yearlyCost': 'Yearly Cost',
    'k8s.costInfoNotAvailable': 'Cost information not available',
    'k8s.imagePlaceholder': 'Enter image address',
    'k8s.key': 'Key',
    'k8s.value': 'Value',
    'k8s.replicasHint': 'Replicas can be set to 0, setting to 0 will stop all Pods',
    'k8s.updateDeploymentFailed': 'Failed to update Deployment',
    'k8s.scaleDeploymentFailed': 'Failed to scale Deployment',
    'k8s.intelligentOptimization': 'Intelligent Optimization',
    'k8s.redeploy': 'Redeploy',
    'k8s.elasticScaling': 'Elastic Scaling',
    'k8s.nodeAffinity': 'Node Affinity',
    'k8s.schedulingToleration': 'Scheduling Toleration',
    'k8s.resourceProfile': 'Resource Profile',
    'k8s.upgradeStrategy': 'Upgrade Strategy',
    'k8s.cloneCreate': 'Clone Create',
    'k8s.rollback': 'Rollback',
    'k8s.confirmRedeploy': 'Are you sure you want to redeploy this Deployment?',
    'k8s.confirmDeleteDeployment': 'Are you sure you want to delete this Deployment? This action cannot be undone.',
    'k8s.redeployFailed': 'Failed to redeploy',
    'k8s.deleteDeploymentFailed': 'Failed to delete Deployment',
    'k8s.confirmDeleteStatefulSet': 'Are you sure you want to delete this StatefulSet? This action cannot be undone.',
    'k8s.confirmDeleteDaemonSet': 'Are you sure you want to delete this DaemonSet? This action cannot be undone.',
    'k8s.confirmDeleteJob': 'Are you sure you want to delete this Job? This action cannot be undone.',
    'k8s.confirmDeleteCronJob': 'Are you sure you want to delete this CronJob? This action cannot be undone.',
    'k8s.deleteStatefulSetFailed': 'Failed to delete StatefulSet',
    'k8s.updateStatefulSetFailed': 'Failed to update StatefulSet',
    'k8s.scaleStatefulSetFailed': 'Failed to scale StatefulSet',
    'k8s.cpuMemory': 'CPU (cores) / Memory',
    'k8s.cores': 'cores',
    'k8s.statusDetails': 'Status Details',
    'k8s.content': 'Content',
    'k8s.message': 'Message',
    'k8s.noConditions': 'No conditions',
    'k8s.creator': 'Creator',
    'k8s.initContainers': 'Init Containers',
    'k8s.noContainers': 'No containers',
    'k8s.noInitContainers': 'No init containers',
    'k8s.kind': 'Kind',
    'k8s.noOwnerRefs': 'No owner references',
    'k8s.viewLogs': 'View Logs',
    'k8s.diagnose': 'Diagnose',
  },
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('zh-CN')
  const hasFetchedRef = useRef(false) // 使用 ref 标记是否已尝试获取，避免重复调用

  useEffect(() => {
    // 从后端获取用户的语言偏好（仅在用户已登录时，且只获取一次）
    const fetchLanguage = async () => {
      // 如果已经尝试过获取，不再重复获取
      if (hasFetchedRef.current) {
        return
      }

      const token = localStorage.getItem('token')
      if (!token) {
        // 用户未登录，使用默认语言，标记为已处理
        hasFetchedRef.current = true
        return
      }
      
      // 标记为已尝试获取
      hasFetchedRef.current = true
      
      try {
        const response = await api.get('/preference')
        if (response.data.data && response.data.data.language) {
          setLanguage(response.data.data.language)
        }
      } catch (err) {
        // 401 错误表示未授权，可能是 token 过期或无效，静默处理
        if (err.response?.status === 401) {
          console.warn('获取语言偏好失败: 未授权，使用默认语言')
          // 清除无效的 token
          localStorage.removeItem('token')
        } else {
          console.error('获取语言偏好失败:', err)
        }
        // 使用默认语言
      }
    }
    fetchLanguage()
  }, []) // 空依赖数组，只在组件挂载时执行一次

  const changeLanguage = async (newLanguage) => {
    setLanguage(newLanguage)
    // 更新后端偏好设置（仅在用户已登录时）
    const token = localStorage.getItem('token')
    if (!token) {
      // 用户未登录，不更新后端
      return
    }
    
    try {
      await api.put('/preference', { language: newLanguage })
    } catch (err) {
      // 401 错误表示未授权，静默处理
      if (err.response?.status === 401) {
        console.warn('更新语言偏好失败: 未授权')
      } else {
        console.error('更新语言偏好失败:', err)
      }
    }
  }

  const t = (key) => {
    return translations[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
